### Here we will train a neural network model which will classify a Bank note is Forgery or not

In [1]:
import numpy as np
import pandas as pd
from numpy import genfromtxt
import keras
from sklearn.preprocessing import MinMaxScaler

In [2]:
from sklearn.model_selection import train_test_split 

In [3]:
data = genfromtxt('bank_note_data.txt', delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
data.shape

(1372, 5)

In [6]:
type(data)

numpy.ndarray

In [7]:
features = data[:,0:4]
label = data[:,4]

In [8]:
features.shape

(1372, 4)

In [9]:
label.shape

(1372,)

In [10]:
pd.DataFrame(label).isna().sum()

0    0
dtype: int64

In [11]:
# Train Test Split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(features,label,test_size=0.2,random_state=42)

In [14]:
# y_test

### Standardizing the Train & Test data for better training & result

In [15]:
standardizing_object = MinMaxScaler()

In [16]:
standardizing_object.fit(X_train)

MinMaxScaler()

In [17]:
X_train_scaled = standardizing_object.transform(X_train)
X_test_scaled = standardizing_object.transform(X_test)

In [18]:
X_train_scaled.shape

(1097, 4)

In [19]:
X_train.shape

(1097, 4)

In [20]:
X_test_scaled.shape

(275, 4)

In [21]:
X_test.shape

(275, 4)

In [22]:
X_test_scaled

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.75753773, 0.34889447, 0.37966768, 0.81250432],
       [0.48778747, 0.82175665, 0.09174727, 0.56211079],
       [0.70853615, 0.92621058, 0.07349701, 0.38693083]])

In [24]:
X_test_scaled.max(), X_test_scaled.min()

(1.02679563427227, -0.0010694864308909147)

In [25]:
X_test.max(), X_test.min()

(15.5573, -13.2869)

In [23]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.4626  , -4.449   ,  3.5427  ,  0.15429 ],
       [-0.278   ,  8.1881  , -3.1338  , -2.5276  ],
       [ 2.7831  , 10.9796  , -3.557   , -4.4039  ]])

### Building the network with Keras

In [26]:
from keras.models import Sequential
from keras.layers import Dense
from keras.metrics import accuracy_metrics, accuracy, confusion_metrics

In [27]:
model = Sequential()

# Input Layer
model.add(Dense(units=4,input_dim=4, activation='relu'))

# Hidden Layer
model.add(Dense(units=8, activation='relu'))

#Output Layer
model.add(Dense(units=1, activation='sigmoid'))

### Compiling the neural network model

In [33]:
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

### Training/fitting the Deep Neural Network model

In [35]:
model.fit(x=X_train_scaled,y=y_train,epochs=100,verbose=2)

Epoch 1/100
35/35 - 0s - loss: 0.0843 - accuracy: 0.9708 - 20ms/epoch - 567us/step
Epoch 2/100
35/35 - 0s - loss: 0.0819 - accuracy: 0.9681 - 14ms/epoch - 412us/step
Epoch 3/100
35/35 - 0s - loss: 0.0804 - accuracy: 0.9708 - 13ms/epoch - 369us/step
Epoch 4/100
35/35 - 0s - loss: 0.0780 - accuracy: 0.9727 - 13ms/epoch - 383us/step
Epoch 5/100
35/35 - 0s - loss: 0.0779 - accuracy: 0.9727 - 13ms/epoch - 380us/step
Epoch 6/100
35/35 - 0s - loss: 0.0758 - accuracy: 0.9708 - 13ms/epoch - 374us/step
Epoch 7/100
35/35 - 0s - loss: 0.0730 - accuracy: 0.9736 - 13ms/epoch - 381us/step
Epoch 8/100
35/35 - 0s - loss: 0.0720 - accuracy: 0.9763 - 13ms/epoch - 383us/step
Epoch 9/100
35/35 - 0s - loss: 0.0699 - accuracy: 0.9754 - 13ms/epoch - 365us/step
Epoch 10/100
35/35 - 0s - loss: 0.0688 - accuracy: 0.9717 - 13ms/epoch - 383us/step
Epoch 11/100
35/35 - 0s - loss: 0.0690 - accuracy: 0.9717 - 13ms/epoch - 383us/step
Epoch 12/100
35/35 - 0s - loss: 0.0665 - accuracy: 0.9727 - 13ms/epoch - 376us/step
E

### Evaluating the Model

In [53]:
y_pred = (model.predict(X_test_scaled)>0.5).astype('int')

9/9 [==============================] - 0s 734us/step


In [47]:
# y_pred = model.predict(X_test_scaled)

In [55]:
# accuracy(y_test,y_pred)

In [59]:
model.metrics_names

['loss', 'accuracy']

In [60]:
model.evaluate(X_test_scaled,y_test)

9/9 [==============================] - 0s 493us/step - loss: 0.0400 - accuracy: 0.9818


[0.04004696384072304, 0.9818181991577148]

## Confusion Matrix

In [66]:
from keras.metrics import confusion_metrics
from sklearn.metrics import confusion_matrix, classification_report

In [65]:
confusion_matrix(y_test,y_pred)

array([[145,   3],
       [  2, 125]])

In [68]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.99      0.98      0.98       148
         1.0       0.98      0.98      0.98       127

    accuracy                           0.98       275
   macro avg       0.98      0.98      0.98       275
weighted avg       0.98      0.98      0.98       275



In [69]:
model.save('mymodel.h5')

In [70]:
from keras.models import load_model

In [71]:
model1 = load_model('mymodel.h5')

In [74]:
X_test_scaled

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.75753773, 0.34889447, 0.37966768, 0.81250432],
       [0.48778747, 0.82175665, 0.09174727, 0.56211079],
       [0.70853615, 0.92621058, 0.07349701, 0.38693083]])

In [75]:
sample_query = [[0.91158363, 0.57924916, 0.43830875, 0.40392598]]

In [76]:
(model1.predict(sample_query)>0.5).astype('int32')

1/1 [==============================] - 0s 26ms/step


array([[0]], dtype=int32)

In [77]:
model1