In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, Lasso
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.datasets import make_regression
from sklearn.compose import ColumnTransformer
# from opencv import *

In [22]:
np.random.seed(101)

In [23]:
arr1 = np.random.randint(0,100,10)

In [24]:
arr2 = np.random.randint(0,100,10)

In [25]:
arr1

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [26]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [27]:
arr1.max()

95

In [29]:
arr1.argmax()

0

In [30]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
arr1.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [35]:
arr1.min()

9

In [36]:
arr1.argmin()

7

In [37]:
matrix = np.random.randint(1,100,10).reshape((5,2))

In [38]:
matrix.shape

(5, 2)

In [39]:
matrix

array([[50, 84],
       [ 9, 30],
       [60, 35],
       [45, 73],
       [20, 11]])

In [41]:
matrix[0,0]

50

In [44]:
mat = np.arange(0,100).reshape(10,10)

In [46]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
mat[5,5:]

array([55, 56, 57, 58, 59])

In [47]:
mat[5,5:].shape

(5,)

In [48]:
mat.shape

(10, 10)

In [49]:
mat.size

100

In [50]:
mat.ndim

2

In [51]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr_3d = np.arange(0,18).reshape((3,2,3))

In [59]:
arr_3d.shape

(3, 2, 3)

In [60]:
arr_3d.size

18

In [61]:
arr_3d.ndim

3

In [63]:
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [66]:
arr_3d[0:, 0, 1]

array([ 1,  7, 13])